apiVersion: skaffold/v2alpha3
kind: Config
build:
  googleCloudBuild:
    projectId: ticketing-dev-401911
  artifacts:
    - image: us.gcr.io/ticketing-dev-401911/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
